INITIAL_POSITIONS = [
    {
        'id': 'pos-pres',
        'title': 'President',
        'description': 'Executive Leader of BAMSSA, Chief Spokesperson and coordinator of association activities.',
        'order': 1,
        'maxSelections': 1,
    },
    {
        'id': 'pos-vp',
        'title': 'Vice President',
        'description': 'Head of Academic Affairs, Committee of Halls, and Deputy to the President.',
        'order': 2,
        'maxSelections': 1,
    },
    {
        'id': 'pos-sec-gen',
        'title': 'Secretary General',
        'description': 'Chief Administrative Officer, custodian of official records, Secretariat and correspondence.',
        'order': 3,
        'maxSelections': 1,
    },
    {
        'id': 'pos-fin-sec',
        'title': 'Financial Secretary',
        'description': 'Oversees financial books, dues reconciliation, and fiscal compliance with ELECO audits.',
        'order': 4,
        'maxSelections': 1,
    },
    {
        'id': 'pos-socials',
        'title': 'Director of Socials',
        'description': 'Plans BAMSSA Health Week, Medical Gala Night, cultural symposiums and student welfare events.',
        'order': 5,
        'maxSelections': 1,
    },
    {
        'id': 'pos-sports',
        'title': 'Director of Sports',
        'description': 'Coordinates inter-departmental Dean’s Cup, indoor games, and wellness tournaments.',
        'order': 6,
        'maxSelections': 1,
    },
    {
        'id': 'pos-pro',
        'title': 'Public Relations Officer (PRO)',
        'description': 'Information dissemination, media outreach, social channels and brand management.',
        'order': 7,
        'maxSelections': 1,
    },
    {
        'id': 'pos-welfare',
        'title': 'Welfare Officer',
        'description': 'Monitors lecture hall conditions, laboratory resources, and student emergency aid fund.',
        'order': 8,
        'maxSelections': 1,
    },
]

INITIAL_CANDIDATES = [
    {
        'id': 'cand-pres-1',
        'positionId': 'pos-pres',
        'fullName': 'Chidubem Emmanuel Okoye',
        'department': 'Anatomy',
        'level': '300L',
        'cgpaRange': '4.62 / 5.0 (First Class)',
        'photoUrl': 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
        'tagline': '“Transforming BMS: Research Grants, Modern Cadaver Lab Equipment & Transparent Leadership”',
        'manifesto': [
            'Establish the BAMSSA Undergraduate Research Innovation Fund in partnership with UniPort Alumni.',
            'Refurbish departmental student study hubs with 24/7 power backup and high-speed Wi-Fi.',
            'Quarterly town halls and open ledger publication of all association financial accounts.'
        ],
        'runningMate': {'name': 'Blessing Tariere George', 'department': 'Psychology', 'level': '300L'},
        'approvedByEleco': True,
    },
    {
        'id': 'cand-pres-2',
        'positionId': 'pos-pres',
        'fullName': 'David Tamunotonye Briggs',
        'department': 'Psychology',
        'level': '300L',
        'cgpaRange': '4.55 / 5.0 (First Class)',
        'photoUrl': 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
        'tagline': '“Action Over Words: Practical Clinical Workshops, Lab Safety & Student Welfare”',
        'manifesto': [
            'Procurement of modern digital ECG and Spirometry diagnostic kits for Physiology training.',
            'Establishment of an emergency distress welfare fund for indigent medical science scholars.',
            'Annual BAMSSA International Health Symposium connecting students to global residency programs.'
        ],
        'runningMate': {'name': 'Kelechi Stephanie Nwosu', 'department': 'Psychology', 'level': '300L'},
        'approvedByEleco': True,
    },
    {
        'id': 'cand-vp-1',
        'positionId': 'pos-vp',
        'fullName': 'Amina Zainab Bello',
        'department': 'Psychology',
        'level': '300L',
        'cgpaRange': '4.48 / 5.0 (Second Class Upper)',
        'photoUrl': 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80',
        'tagline': '“Bridging Academics and Practice: Mentorship, Reagents Availability & Career Guidance”',
        'manifesto': [
            'Guaranteed subsidization of laboratory practical reagents through Faculty subventions.',
            'Bi-monthly peer tutoring circles for high-difficulty courses.',
            'Career bridge webinars with pharmaceutical R&D firms and clinical biochemistry leaders.'
        ],
        'approvedByEleco': True,
    },
    {
        'id': 'cand-vp-2',
        'positionId': 'pos-vp',
        'fullName': 'Godswill Ebuka Nnamdi',
        'department': 'Psychology',
        'level': '300L',
        'cgpaRange': '4.35 / 5.0 (Second Class Upper)',
        'photoUrl': 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
        'tagline': '“Student-Centered Advocacy: Safe Study Spaces & Academic Resource Bank”',
        'manifesto': [
            'Comprehensive digital past questions and validated marking schemes repository.',
            'Advocacy with faculty board for humane continuous assessment and test timetables.',
            'Inter-college quiz competitions with cash scholarships for top performers.'
        ],
        'approvedByEleco': True,
    },
    {
        'id': 'cand-sec-1',
        'positionId': 'pos-sec-gen',
        'fullName': 'Faith Olamide Adeleke',
        'department': 'Psychology',
        'level': '300L',
        'cgpaRange': '4.68 / 5.0',
        'photoUrl': 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=400&q=80',
        'tagline': '“Digital Secretariat: Instant Electronic Bulletins & Transparent Governance”',
        'manifesto': [
            'Launch the BAMSSA WhatsApp and Telegram automated information bot for notices.',
            'Publication of meeting minutes within 24 hours of executive sittings.',
            'Seamless digital dues receipt and clearance verification system.'
        ],
        'approvedByEleco': True,
    },
    {
        'id': 'cand-sec-2',
        'positionId': 'pos-sec-gen',
        'fullName': 'Victor Somtochukwu Eze',
        'department': 'Anatomy',
        'level': '300L',
        'cgpaRange': '4.21 / 5.0',
        'photoUrl': 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=400&q=80',
        'tagline': '“Accuracy, Efficiency, and Prompt Association Documentation”',
        'manifesto': [
            'Modern physical archiving of BAMSSA historical records in the Faculty Library.',
            'Structured feedback form system allowing students to directly query executive departments.',
            'Timely accreditation processing for all university and regional conferences.'
        ],
        'approvedByEleco': True,
    },
    {
        'id': 'cand-fin-1',
        'positionId': 'pos-fin-sec',
        'fullName': 'Precious Ijeoma Kalu',
        'department': 'Psychology',
        'level': '300L',
        'cgpaRange': '4.71 / 5.0',
        'photoUrl': 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?auto=format&fit=crop&w=400&q=80',
        'tagline': '“Zero-Leakage Treasury: Real-Time Financial Dashboards & Audit Rigor”',
        'manifesto': [
            'Live online income and expenditure dashboard open to all BAMSSA dues-paying members.',
            'Strict adherence to budget ceilings with bi-weekly audit reports.',
            'Multiple convenient digital payment gateways for seamless dues collection.'
        ],
        'approvedByEleco': True,
    },
    {
        'id': 'cand-soc-1',
        'positionId': 'pos-socials',
        'fullName': 'Favour Tonye West',
        'department': 'Psychology',
        'level': '300L',
        'cgpaRange': '4.15 / 5.0',
        'photoUrl': 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=400&q=80',
        'tagline': '“Unforgettable Health Week: Premium Medical Gala, Cultural Night & Comedy Fest”',
        'manifesto': [
            'Host the biggest BAMSSA Health Week in UNIPORT history with major pharmaceutical sponsors.',
            'Reinvent the BMS Dinner & Awards Night with subsidized tickets for 200L students.',
            'Stress-relief game nights and mental health decompression hubs during exam periods.'
        ],
        'approvedByEleco': True,
    },
]

INITIAL_VOTERS = [
    {
        'id': 'voter-demo-doe',
        'matricNumber': 'U2021/5530001',
        'fullName': 'John Doe',
        'department': 'Anatomy',
        'level': '300L',
        'email': 'student@uniport.edu.ng',
        'phone': '+234 802 334 9901',
        'isEligible': True,
        'isAccredited': True,
        'hasVoted': False,
        'voterPin': '4021',
        'verificationStatus': 'approved',
        'registeredAt': 'Oct 11, 04:20 PM',
        'accreditationTime': '2026-08-20T08:00:00Z',
    },
    {
        'id': 'voter-1',
        'matricNumber': 'U2022/5570012',
        'fullName': 'Chidera Somtochukwu Anyanwu',
        'department': 'Anatomy',
        'level': '300L',
        'email': 'chidera.anyanwu@uniport.edu.ng',
        'phone': '+234 814 552 8901',
        'isEligible': True,
        'isAccredited': True,
        'hasVoted': False,
        'voterPin': '4829',
        'verificationStatus': 'approved',
        'registeredAt': 'Oct 11, 02:10 PM',
        'accreditationTime': '2026-08-20T08:14:22Z',
    },
    {
        'id': 'voter-2',
        'matricNumber': 'U2021/5568045',
        'fullName': 'Ibrahim Olanrewaju Musa',
        'department': 'Psychology',
        'level': '300L',
        'email': 'ibrahim.musa@uniport.edu.ng',
        'phone': '+234 803 112 4478',
        'isEligible': True,
        'isAccredited': True,
        'hasVoted': True,
        'voterPin': '7391',
        'verificationStatus': 'approved',
        'registeredAt': 'Oct 11, 11:05 AM',
        'accreditationTime': '2026-08-20T07:45:10Z',
        'votedTime': '2026-08-20T08:30:15Z',
        'ballotReceiptHash': '0x8F9C2B7A1E4D6380A91DFF7E2459',
    },
    {
        'id': 'voter-6',
        'matricNumber': 'U2020/5565011',
        'fullName': 'Osasere Harrison Ighodaro',
        'department': 'Anatomy',
        'level': '300L',
        'email': 'osasere.ighodaro@uniport.edu.ng',
        'phone': '+234 809 334 5567',
        'isEligible': True,
        'isAccredited': True,
        'hasVoted': True,
        'voterPin': '3319',
        'verificationStatus': 'approved',
        'registeredAt': 'Oct 08, 04:45 PM',
        'accreditationTime': '2026-08-20T07:10:05Z',
        'votedTime': '2026-08-20T08:05:44Z',
        'ballotReceiptHash': '0x3E1C89F70D421BA890EEA7B90412',
    },
    {
        'id': 'voter-5',
        'matricNumber': 'U2022/5571144',
        'fullName': 'Folashade Esther Adeleke',
        'department': 'Psychology',
        'level': '300L',
        'email': 'folashade.adeleke@uniport.edu.ng',
        'phone': '+234 708 990 1234',
        'isEligible': False,
        'isAccredited': False,
        'hasVoted': False,
        'voterPin': '6038',
        'verificationStatus': 'rejected',
        'registeredAt': 'Oct 09, 10:00 AM',
        'rejectionReason': 'Non-matching faculty registration record (Cross-faculty transfer pending)',
    },
]

INITIAL_AUDIT_LOGS = []

DEPARTMENT_STATS = {
    'Anatomy': {'eligible': 680, 'accredited': 410, 'voted': 285},
    'Psychology': {'eligible': 640, 'accredited': 395, 'voted': 270},
}
